# Generated by Django 6.1 on 2026-08-09 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='insurance/')),
                ('is_active', models.BooleanField(default=True)),
                ('coverage_rate', models.PositiveIntegerField(default=80, help_text='% de prise en charge')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('paid', 'Payée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='orders.order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.insuranceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('moov', 'Moov Money'), ('airtel', 'Airtel Money'), ('card', 'Carte bancaire'), ('cod', 'Paiement à la livraison'), ('pharmacy', 'Paiement en pharmacie'), ('insurance', 'Assurance maladie'), ('transfer', 'Virement')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('is_deposit', models.BooleanField(default=False, help_text='Acompte COD')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('essential', 'Essentiel'), ('professional', 'Professionnel'), ('enterprise', 'Entreprise'), ('none', 'Aucun')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente de paiement'), ('expired', 'Expiré'), ('cancelled', 'Résilié')], default='pending', max_length=20)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
