# Generated by Django 6.1 on 2026-08-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
