# Generated by Django 6.1 on 2026-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_patient_access_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprovider',
            name='annual_cap',
            field=models.PositiveIntegerField(default=500000, help_text='Plafond annuel de prise en charge par bénéficiaire (FCFA)'),
        ),
    ]
