# Generated by Django 6.1 on 2026-08-29 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_handoff_fields'),
        ('orders', '0006_insurance_checkout'),
        ('payments', '0004_insurance_checkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=5, help_text='Commission plateforme sur le panier (%)', max_digits=5)),
                ('payout_delay_days', models.PositiveSmallIntegerField(default=2, help_text='Délai de versement pharmacie (jours)')),
                ('daily_transaction_cap', models.PositiveIntegerField(default=500000, help_text='Plafond paiement client / jour (FCFA)')),
                ('cod_deposit_rate', models.PositiveSmallIntegerField(default=20, help_text='Acompte COD (% du reste à charge)')),
                ('cod_deposit_min', models.PositiveIntegerField(default=500, help_text='Acompte COD minimum (FCFA)')),
                ('courier_base_fee', models.PositiveIntegerField(default=1500, help_text='Rémunération de base par course (FCFA)')),
                ('courier_per_km_fee', models.PositiveIntegerField(default=200, help_text='Bonus distance par km (FCFA)')),
                ('courier_express_bonus', models.PositiveIntegerField(default=500, help_text='Bonus livraison express (FCFA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres paiement plateforme',
                'verbose_name_plural': 'Paramètres paiement plateforme',
            },
        ),
        migrations.CreateModel(
            name='CourierEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.PositiveIntegerField(default=0)),
                ('distance_bonus', models.PositiveIntegerField(default=0)),
                ('express_bonus', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Versé')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_earnings', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='deliveries.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_base', models.PositiveIntegerField(default=0, help_text='Sous-total − remise')),
                ('platform_commission', models.PositiveIntegerField(default=0)),
                ('pharmacy_net', models.PositiveIntegerField(default=0)),
                ('delivery_fee', models.PositiveIntegerField(default=0)),
                ('courier_earning', models.PositiveIntegerField(default=0)),
                ('platform_delivery_margin', models.PositiveIntegerField(default=0)),
                ('pharmacy_payout_status', models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Programmé'), ('paid', 'Versé')], default='pending', max_length=20)),
                ('courier_payout_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Versé'), ('na', 'Sans livraison')], default='na', max_length=20)),
                ('payout_due_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
