# Generated by Django 6.1 on 2026-08-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_insuranceclaim_review_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurerFraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('alert_type', models.CharField(choices=[('suspicious', 'Demande suspecte'), ('overbilling', 'Sur-facturation'), ('document', 'Document suspect'), ('abuse', 'Utilisation anormale')], max_length=20)),
                ('level', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevé'), ('medium', 'Moyen'), ('low', 'Faible')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'En cours'), ('analysis', 'En analyse'), ('resolved', 'Résolue')], default='open', max_length=12)),
                ('holder_name', models.CharField(max_length=200)),
                ('holder_sub', models.CharField(blank=True, max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='payments.insuranceclaim')),
                ('insurance_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='payments.insuranceprovider')),
            ],
            options={
                'verbose_name': 'Alerte fraude assureur',
                'verbose_name_plural': 'Alertes fraude assureur',
                'ordering': ['-detected_at'],
            },
        ),
    ]
