# Generated by Django 6.1 on 2026-08-30 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_insurer_portal_dynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='essentiel, entreprise, plus…', max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('premium_amount', models.PositiveIntegerField(help_text='Cotisation FCFA par période')),
                ('coverage_rate', models.PositiveSmallIntegerField(default=80)),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel')], default='monthly', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='payments.insuranceprovider')),
            ],
            options={
                'verbose_name': "Formule d'abonnement assurance",
                'verbose_name_plural': "Formules d'abonnement assurance",
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'code'), name='uniq_insurance_plan_per_provider')],
            },
        ),
    ]
