# Generated by Django 6.1 on 2026-08-09 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('placement', models.CharField(choices=[('home_top', 'Accueil — sous le hero'), ('home_mid', 'Accueil — milieu de page'), ('home_bottom', 'Accueil — bas de page'), ('catalog', 'Catalogue'), ('sidebar', 'Latéral')], default='home_mid', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Plus élevé = affiché en premier')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Votre pharmacie en ligne gabonaise', max_length=120, verbose_name='Sur-titre')),
                ('title', models.CharField(default='Médicaments & parapharmacie,', max_length=200, verbose_name='Titre (ligne 1)')),
                ('title_accent', models.CharField(default='à portée de clic', max_length=120, verbose_name='Titre accentué (ligne 2)')),
                ('description', models.TextField(default='Recherchez un médicament, comparez les pharmacies partenaires et faites-vous livrer à Libreville — en toute sécurité.')),
                ('cta1_label', models.CharField(default='Voir tous les médicaments', max_length=80)),
                ('cta1_url', models.CharField(default='/recherche/', max_length=255)),
                ('cta2_label', models.CharField(default='Pharmacies à proximité', max_length=80)),
                ('cta2_url', models.CharField(default='/pharmacies/', max_length=255)),
                ('hero_image', models.ImageField(blank=True, help_text='Image / logo affiché à droite du hero. Si vide, logo plateforme par défaut.', null=True, upload_to='site/hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero accueil',
                'verbose_name_plural': 'Hero accueil',
            },
        ),
        migrations.CreateModel(
            name='PharmacistTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='Santé', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tips/')),
                ('icon', models.CharField(blank=True, default='health_and_safety', help_text="Nom d'icône Material Symbols si pas d'image", max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacist_tips', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'Conseil pharmacien',
                'verbose_name_plural': 'Conseils pharmaciens',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
