# Generated by Django 6.1 on 2026-08-30 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ad_upload_to_banners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(choices=[('vaccination', 'Vaccination (PEV / fièvre jaune, rougeole…)'), ('malaria', 'Lutte antipaludisme (MILDA, TPI)'), ('maternal', 'Santé maternelle et néonatale'), ('cholera', 'Prévention choléra & eau potable'), ('hiv', 'VIH / dépistage & prévention'), ('ncd', 'Maladies non transmissibles (diabète, HTA)'), ('nutrition', 'Nutrition infantile'), ('tobacco', 'Lutte anti-tabac'), ('other', 'Autre campagne')], default='vaccination', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('planned', 'Planifiée'), ('active', 'En cours'), ('completed', 'Terminée'), ('paused', 'Suspendue')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('partner', models.CharField(blank=True, help_text='Partenaire : MSNS, OMS, UNICEF, CNAMGS…', max_length=120)),
                ('region_slugs', models.JSONField(blank=True, default=list, help_text='Provinces ciblées (slugs gabon-provinces). Vide = national.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_population', models.PositiveIntegerField(default=0)),
                ('people_reached', models.PositiveIntegerField(default=0)),
                ('doses_target', models.PositiveIntegerField(blank=True, default=0)),
                ('doses_administered', models.PositiveIntegerField(blank=True, default=0)),
                ('pharmacies_involved', models.PositiveIntegerField(default=0, help_text='Points de distribution déclarés (pharmacies partenaires).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne de santé',
                'verbose_name_plural': 'Campagnes de santé',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
