# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_health_campaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=500, unique=True)),
                ("data", models.BinaryField()),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fichier média",
                "verbose_name_plural": "Fichiers médias",
            },
        ),
    ]
