# Generated by Django 6.1 on 2026-08-09 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Libreville', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(default='Estuaire', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacies/logos/')),
                ('logo_color', models.CharField(default='green', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'En attente'), ('suspended', 'Suspendue'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('is_24h', models.BooleanField(default=False)),
                ('is_on_duty', models.BooleanField(default=False, verbose_name='Pharmacie de garde')),
                ('opening_hours', models.CharField(blank=True, default='08:00 – 20:00', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('compliance_score', models.PositiveIntegerField(default=100)),
                ('subscription_plan', models.CharField(choices=[('essential', 'Essentiel'), ('professional', 'Professionnel'), ('enterprise', 'Entreprise'), ('none', 'Aucun')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='pharmacies/docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pharmacies.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pharmacies.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pharmacy', 'user')},
            },
        ),
    ]
