# Generated by Django 6.1 on 2026-08-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydocument',
            name='expires_at',
            field=models.DateField(blank=True, help_text="Date d'expiration du document (agrément, RCCM…). Alerte J-30.", null=True),
        ),
    ]
