# Generated by Django 6.1 on 2026-08-29 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_pharmacy_delivery_promise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Matricule interne', max_length=20)),
                ('job_role', models.CharField(choices=[('owner', 'Titulaire / Gérant'), ('manager', 'Adjoint / Gestionnaire'), ('pharmacist', 'Pharmacien'), ('preparer', 'Préparateur'), ('cashier', 'Caissier'), ('intern', 'Stagiaire')], default='pharmacist', max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('interim', 'Intérim')], default='cdi', max_length=20)),
                ('hired_at', models.DateField(default=django.utils.timezone.localdate)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('base_salary', models.PositiveIntegerField(default=0, help_text='Salaire mensuel de base (FCFA)')),
                ('national_id', models.CharField(blank=True, max_length=40, verbose_name='N° CNI')),
                ('professional_license', models.CharField(blank=True, max_length=40, verbose_name='N° ordre / RPPS')),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pharmacies.pharmacy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_employments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé pharmacie',
                'verbose_name_plural': 'Employés pharmacie',
                'ordering': ['pharmacy__name', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='pharmacies.pharmacyemployee')),
            ],
            options={
                'ordering': ['shift_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('base_salary', models.PositiveIntegerField(default=0)),
                ('bonus', models.PositiveIntegerField(default=0)),
                ('deductions', models.PositiveIntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('net_salary', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('paid', 'Payé')], default='draft', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='pharmacies.pharmacyemployee')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('leave', 'Congé payé'), ('sick', 'Maladie'), ('training', 'Formation'), ('unpaid', 'Sans solde'), ('other', 'Autre')], default='leave', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_reviewed', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='pharmacies.pharmacyemployee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='pharmacyemployee',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'employee_code'), name='uniq_pharmacy_employee_code'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacyemployee',
            unique_together={('pharmacy', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeshift',
            unique_together={('employee', 'shift_date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='employeepayslip',
            unique_together={('employee', 'period_year', 'period_month')},
        ),
    ]
