# Generated by Django 6.1 on 2026-08-24 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0003_order_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earn', 'Gain'), ('spend', 'Dépense'), ('expire', 'Expiration'), ('adjust', 'Ajustement')], default='earn', max_length=20)),
                ('points', models.IntegerField(help_text='Positif = crédit, négatif = débit')),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement fidélité',
                'verbose_name_plural': 'Mouvements fidélité',
                'ordering': ['-created_at'],
            },
        ),
    ]
