# Generated by Django 6.1 on 2026-08-29 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cdc_loyalty_support_insurance'),
        ('payments', '0003_patient_access_purchase'),
        ('pharmacies', '0004_pharmacy_personnel_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='Pharmacie de rattachement (une seule à la fois)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers', to='pharmacies.pharmacy'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_region',
            field=models.CharField(blank=True, help_text='Région de rattachement (superviseur régional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client / Patient'), ('pharmacist', 'Pharmacien'), ('courier', 'Livreur'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur'), ('authority', 'Autorité Sanitaire'), ('support', 'Support'), ('regional_supervisor', 'Superviseur régional'), ('partner', 'Institution partenaire')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('insurer', 'Assureur / Mutuelle'), ('lab', 'Laboratoire'), ('wholesaler', 'Grossiste')], max_length=20)),
                ('organization_name', models.CharField(max_length=200)),
                ('insurance_provider', models.ForeignKey(blank=True, help_text='Assureur lié (si type assureur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_users', to='payments.insuranceprovider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil partenaire',
                'verbose_name_plural': 'Profils partenaires',
            },
        ),
    ]
