# Generated by Django 6.1 on 2026-08-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cdc_roles_partner_regional'),
        ('payments', '0004_insurance_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='insurance_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profiles', to='payments.insuranceprovider'),
        ),
    ]
