# Generated by Django 6.1 on 2026-08-29 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_insurance_checkout'),
        ('orders', '0006_insurance_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_1000_fcfa', models.PositiveSmallIntegerField(default=1, help_text='Points gagnés par tranche de 1000 FCFA dépensés')),
                ('points_validity_days', models.PositiveIntegerField(default=365, help_text='Durée de validité des points gagnés (jours)')),
                ('expiry_warning_days', models.PositiveSmallIntegerField(default=30, help_text='Notification avant expiration des points')),
                ('voucher_validity_days', models.PositiveSmallIntegerField(default=90, help_text="Validité d'un bon échangé (jours)")),
                ('bronze_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('silver_discount_percent', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('gold_discount_percent', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
            ],
            options={
                'verbose_name': 'Paramètres fidélité',
                'verbose_name_plural': 'Paramètres fidélité',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reward_type', models.CharField(choices=[('discount_fcfa', 'Réduction (FCFA)'), ('free_delivery', 'Livraison offerte')], max_length=20)),
                ('points_cost', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField(default=0, help_text='Montant FCFA (réduction) — ignoré pour livraison offerte')),
                ('min_level', models.CharField(blank=True, help_text='Palier minimum : decouverte, bronze, argent, or', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Récompense fidélité',
                'verbose_name_plural': 'Récompenses fidélité',
                'ordering': ['sort_order', 'points_cost'],
            },
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='expired_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='expiry_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.loyaltyreward'),
        ),
        migrations.CreateModel(
            name='LoyaltyVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('points_spent', models.PositiveIntegerField()),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('free_delivery', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_vouchers', to='orders.order')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounts.loyaltyreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon fidélité',
                'verbose_name_plural': 'Bons fidélité',
                'ordering': ['-created_at'],
            },
        ),
    ]
