# Generated by Django 6.1 on 2026-08-29 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loyaltyprogramsettings_loyaltyreward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Ministère, Direction, agence…', max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, help_text='Zone de compétence', max_length=100)),
                ('two_factor_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail')], default='email', max_length=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_authorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil autorité sanitaire',
                'verbose_name_plural': 'Profils autorités sanitaires',
            },
        ),
    ]
