# Generated by Django 6.1 on 2026-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authority_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_role_permissions', models.JSONField(blank=True, default=dict, help_text='Rôle métier pharmacie → liste de permissions ERP')),
                ('platform_role_modules', models.JSONField(blank=True, default=dict, help_text='Rôle plateforme → modules back-office admin autorisés')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration des accès',
                'verbose_name_plural': 'Configuration des accès',
            },
        ),
    ]
