# Generated by Django 6.1 on 2026-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_access_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessconfiguration",
            name="portal_role_modules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Rôle portail (autorité, partenaire, livreur…) → modules autorisés",
            ),
        ),
    ]
