# Generated by Django 6.1 on 2026-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_courier_eligibility_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default="Gab'Pharma", max_length=120)),
                ('slogan', models.CharField(default='Votre santé, notre priorité', max_length=200)),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA (XAF)')], default='XAF', max_length=8)),
                ('country', models.CharField(default='Gabon', max_length=80)),
                ('default_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=8)),
                ('date_format', models.CharField(choices=[('d/m/Y', 'JJ/MM/AAAA'), ('m/d/Y', 'MM/JJ/AAAA'), ('Y-m-d', 'AAAA-MM-JJ')], default='d/m/Y', max_length=16)),
                ('timezone', models.CharField(default='Africa/Libreville', max_length=64)),
                ('time_format', models.CharField(choices=[('24', '24 heures'), ('12', '12 heures')], default='24', max_length=4)),
                ('two_factor_required', models.BooleanField(default=True)),
                ('session_expiry_minutes', models.PositiveSmallIntegerField(default=30)),
                ('password_complexity', models.BooleanField(default=True)),
                ('login_attempt_limit', models.PositiveSmallIntegerField(default=5)),
                ('activity_logging', models.BooleanField(default=True)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=16)),
                ('backup_retention_days', models.PositiveSmallIntegerField(default=30)),
                ('scheduled_maintenance', models.BooleanField(default=False)),
                ('integrations', models.JSONField(blank=True, default=dict, help_text='État des intégrations externes (paiement, assurance, livraison…)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres plateforme',
                'verbose_name_plural': 'Paramètres plateforme',
            },
        ),
    ]
