# Generated by Django 6.1 on 2026-08-30 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_partner_insurer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurerPortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='fr', max_length=8)),
                ('timezone', models.CharField(default='Africa/Libreville', max_length=64)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('date_format', models.CharField(default='d/m/Y', max_length=16)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immédiatement'), ('daily', 'Quotidiennement'), ('weekly', 'Hebdomadairement')], default='immediate', max_length=16)),
                ('daily_digest_time', models.TimeField(default='18:00')),
                ('category_preferences', models.JSONField(blank=True, default=dict)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('session_expiry_minutes', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_portal_settings', to='accounts.partnerprofile')),
            ],
            options={
                'verbose_name': 'Paramètres portail assureur',
                'verbose_name_plural': 'Paramètres portail assureur',
            },
        ),
    ]
