# Generated by Django 6.1 on 2026-08-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_partner_subscription'),
        ('payments', '0007_insurer_portal_dynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceMemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('plan', models.CharField(choices=[('essentiel', 'Essentiel'), ('entreprise', 'Santé Entreprise'), ('plus', 'Santé Plus')], default='entreprise', max_length=20)),
                ('premium_amount', models.PositiveIntegerField(default=35000, help_text='Cotisation mensuelle FCFA')),
                ('coverage_rate', models.PositiveSmallIntegerField(default=80)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('suspended', 'Suspendu'), ('expired', 'Expiré'), ('cancelled', 'Résilié')], default='active', max_length=12)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_subscriptions', to='accounts.clientprofile')),
                ('insurance_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_subscriptions', to='payments.insuranceprovider')),
            ],
            options={
                'verbose_name': 'Abonnement assuré',
                'verbose_name_plural': 'Abonnements assurés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PartnerSubscription',
        ),
    ]
