# Generated by Django 6.1 on 2026-08-30 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_member_insurance_subscription'),
        ('payments', '0008_subscription_generalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancemembersubscription',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.insurancesubscriptionplan'),
        ),
        migrations.AddField(
            model_name='insurancemembersubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insurancemembersubscription',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_subscriptions', to='accounts.clientprofile'),
        ),
        migrations.AlterField(
            model_name='insurancemembersubscription',
            name='premium_amount',
            field=models.PositiveIntegerField(default=35000, help_text='Cotisation FCFA'),
        ),
    ]
