# Generated by Django 6.1 on 2026-08-30 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_subscription_generalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('standard', 'Standard'), ('professional', 'Professionnel'), ('enterprise', 'Entreprise')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Montant FCFA pour la période')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente de paiement'), ('expired', 'Expiré'), ('cancelled', 'Résilié')], default='pending', max_length=20)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_subscriptions', to='accounts.partnerprofile')),
            ],
            options={
                'verbose_name': 'Abonnement partenaire plateforme',
                'verbose_name_plural': 'Abonnements partenaires plateforme',
                'ordering': ['-created_at'],
            },
        ),
    ]
