from django.urls import path

from backoffice import client_portal_views
from backoffice import views
from backoffice import prescription_files
from backoffice.pharmacy_personnel import pharmacy_personnel
from backoffice.regional_portal import regional_dashboard
from backoffice.insurer_portal import (
    insurer_claims,
    insurer_claims_approved,
    insurer_claim_detail,
    insurer_claims_pending,
    insurer_claims_rejected,
    insurer_contracts,
    insurer_dashboard,
    insurer_fraud,
    insurer_members,
    insurer_notifications,
    insurer_payments,
    insurer_pharmacies,
    insurer_pharmacy_detail,
    insurer_reports,
    insurer_settings,
    insurer_subscription,
    insurer_support,
    partner_dashboard,
)

urlpatterns = [
    path("", views.backoffice_entry, name="backoffice"),
    path("profil/", views.my_profile, name="bo_my_profile"),
    path(
        "apercu-email-identifiants/",
        views.preview_credentials_email,
        name="bo_preview_credentials_email",
    ),
    path(
        "ordonnance/<int:pk>/fichier/",
        prescription_files.prescription_file_view,
        name="bo_prescription_file",
    ),
    path(
        "commande/<int:order_id>/fichier-ordonnance/",
        prescription_files.order_prescription_file_view,
        name="bo_order_prescription_file",
    ),
    # Admin CRUD
    path("admin/", views.admin_dashboard, name="bo_admin_dashboard"),
    path("admin/utilisateurs/", views.admin_users, name="bo_admin_users"),
    path("admin/autorites/", views.admin_authorities, name="bo_admin_authorities"),
    path("admin/pharmacies/", views.admin_pharmacies, name="bo_admin_pharmacies"),
    path("admin/medicaments/", views.admin_medicines, name="bo_admin_medicines"),
    path("admin/commandes/", views.admin_orders, name="bo_admin_orders"),
    path("admin/livreurs/", views.admin_couriers, name="bo_admin_couriers"),
    path("admin/paiements/", views.admin_payments, name="bo_admin_payments"),
    path("admin/incidents/", views.admin_incidents, name="bo_admin_incidents"),
    path("admin/notifications/", views.admin_notifications, name="bo_admin_notifications"),
    path("admin/assurances/", views.admin_insurance, name="bo_admin_insurance"),
    path(
        "admin/assurances/inscription/<int:profile_id>/",
        views.admin_insurance_review,
        name="bo_admin_insurance_review",
    ),
    path("admin/abonnements/", views.admin_subscriptions, name="bo_admin_subscriptions"),
    path("admin/configuration/", views.admin_access_config, name="bo_admin_access_config"),
    path("admin/parametres/", views.admin_platform_settings, name="bo_admin_platform_settings"),
    path("admin/audit/", views.admin_audit, name="bo_admin_audit"),
    path("admin/hero/", views.admin_hero, name="bo_admin_hero"),
    path("admin/publicites/", views.admin_ads, name="bo_admin_ads"),
    path("admin/conseils/", views.admin_tips, name="bo_admin_tips"),
    # Pharmacie
    path("pharmacie/", views.pharmacy_dashboard, name="bo_pharmacy_dashboard"),
    path("pharmacie/statistiques/", views.pharmacy_stats, name="bo_pharmacy_stats"),
    path("pharmacie/commandes/", views.pharmacy_orders, name="bo_pharmacy_orders"),
    path("pharmacie/commandes/<int:pk>/ordonnance/", views.pharmacy_prescription_detail, name="bo_pharmacy_prescription_detail"),
    path("pharmacie/commandes/<int:pk>/imprimer/", views.pharmacy_order_print, name="bo_pharmacy_order_print"),
    path("pharmacie/commandes/<int:pk>/qr/", views.pharmacy_order_qr, name="bo_pharmacy_order_qr"),
    path("pharmacie/stocks/", views.pharmacy_stocks, name="bo_pharmacy_stocks"),
    path("pharmacie/stocks/<int:stock_id>/fiche/", views.pharmacy_medicine_edit, name="bo_pharmacy_medicine_edit"),
    path("pharmacie/conseils/", views.pharmacy_tips, name="bo_pharmacy_tips"),
    path("pharmacie/messages/", views.pharmacy_messages, name="bo_pharmacy_messages"),
    path("pharmacie/notifications/", views.pharmacy_notifications, name="bo_pharmacy_notifications"),
    path("pharmacie/ma-pharmacie/", views.pharmacy_settings, name="bo_pharmacy_settings"),
    path("pharmacie/abonnement/", views.pharmacy_subscription, name="bo_pharmacy_subscription"),
    path("pharmacie/personnel/", pharmacy_personnel, name="bo_pharmacy_personnel"),
    # Livreur
    path("livreur/", views.courier_dashboard, name="bo_courier_dashboard"),
    path("livreur/livraisons/", views.courier_deliveries, name="bo_courier_deliveries"),
    path("livreur/profil/", views.courier_settings, name="bo_courier_settings"),
    path("livreur/vehicules/", views.courier_vehicles, name="bo_courier_vehicles"),
    path("livreur/incident/<int:delivery_id>/", views.courier_incident, name="bo_courier_incident"),
    # Autorité — stats santé publique
    path("autorite/", views.authority_dashboard, name="bo_authority_dashboard"),
    path("autorite/carte/", views.authority_map, name="bo_authority_map"),
    path("autorite/stocks/", views.authority_stocks, name="bo_authority_stocks"),
    path("autorite/ruptures/", views.authority_ruptures, name="bo_authority_ruptures"),
    path("autorite/alertes/", views.authority_alerts, name="bo_authority_alerts"),
    path("autorite/analyses/", views.authority_trends, name="bo_authority_trends"),
    path("autorite/patients/", views.authority_patients, name="bo_authority_patients"),
    path("autorite/pharmacies/", views.authority_pharmacies, name="bo_authority_pharmacies"),
    path("autorite/conformite/", views.authority_compliance, name="bo_authority_compliance"),
    path("autorite/livraisons/", views.authority_deliveries, name="bo_authority_deliveries"),
    path("autorite/litiges/", views.authority_disputes, name="bo_authority_disputes"),
    path("autorite/rapports/", views.authority_reports, name="bo_authority_reports"),
    path("autorite/campagnes/", views.authority_campaigns, name="bo_authority_campaigns"),
    path("autorite/notifications/", views.authority_notifications, name="bo_authority_notifications"),
    path("autorite/parametres/", views.authority_settings, name="bo_authority_settings"),
    path("autorite/decision/", views.authority_decision, name="bo_authority_decision"),
    # Superviseur régional
    path("regional/", regional_dashboard, name="bo_regional_dashboard"),
    # Compagnie d'assurance
    path("assurance/", insurer_dashboard, name="bo_insurer_dashboard"),
    path("assurance/demandes/", insurer_claims, name="bo_insurer_claims"),
    path("assurance/demandes/<int:claim_id>/", insurer_claim_detail, name="bo_insurer_claim_detail"),
    path("assurance/demandes/en-attente/", insurer_claims_pending, name="bo_insurer_claims_pending"),
    path("assurance/demandes/validees/", insurer_claims_approved, name="bo_insurer_claims_approved"),
    path("assurance/demandes/refusees/", insurer_claims_rejected, name="bo_insurer_claims_rejected"),
    path("assurance/assures/", insurer_members, name="bo_insurer_members"),
    path("assurance/pharmacies/", insurer_pharmacies, name="bo_insurer_pharmacies"),
    path("assurance/pharmacies/<int:pharmacy_id>/", insurer_pharmacy_detail, name="bo_insurer_pharmacy_detail"),
    path("assurance/paiements/", insurer_payments, name="bo_insurer_payments"),
    path("assurance/contrats/", insurer_contracts, name="bo_insurer_contracts"),
    path("assurance/abonnement/", insurer_subscription, name="bo_insurer_subscription"),
    path("assurance/statistiques/", insurer_reports, name="bo_insurer_reports"),
    path("assurance/fraudes/", insurer_fraud, name="bo_insurer_fraud"),
    path("assurance/notifications/", insurer_notifications, name="bo_insurer_notifications"),
    path("assurance/parametres/", insurer_settings, name="bo_insurer_settings"),
    path("assurance/support/", insurer_support, name="bo_insurer_support"),
    path("partenaire/", partner_dashboard, name="bo_partner_dashboard"),
    # Support
    path("support/", views.support_dashboard, name="bo_support_dashboard"),
    path("support/reclamations/", views.support_tickets, name="bo_support_tickets"),
    # Client
    path("client/", views.client_dashboard, name="bo_client_dashboard"),
    path("client/commandes/", views.client_orders, name="bo_client_orders"),
    path("client/commandes/<int:pk>/", views.client_order_detail, name="bo_client_order_detail"),
    path("client/ordonnances/", views.client_prescriptions, name="bo_client_prescriptions"),
    path("client/notifications/", views.client_notifications, name="bo_client_notifications"),
    path("client/fidelite/", views.client_loyalty, name="bo_client_loyalty"),
    path("client/reclamations/", views.client_support, name="bo_client_support"),
    path("client/profil/", views.client_settings, name="bo_client_settings"),
    path("client/profil/informations/", views.client_profile_personal, name="bo_client_profile_personal"),
    path("client/profil/adresse/", views.client_profile_address, name="bo_client_profile_address"),
    path("client/profil/paiement/", views.client_profile_payment, name="bo_client_profile_payment"),
    path("client/profil/preferences/", views.client_profile_preferences, name="bo_client_profile_preferences"),
    path("client/profil/securite/", views.client_profile_security, name="bo_client_profile_security"),
    path("client/profil/confidentialite/", views.client_profile_privacy, name="bo_client_profile_privacy"),
    path("client/parametres/", views.client_parametres, name="bo_client_parametres"),
    path("client/sessions/", views.client_sessions, name="bo_client_sessions"),
    path("client/a-propos/", views.client_about, name="bo_client_about"),
    path("client/cgu/", views.client_terms, name="bo_client_terms"),
    # Parcours patient (reste dans l'espace client)
    path("client/catalogue/", client_portal_views.client_catalog, name="bo_client_catalog"),
    path("client/favoris/", client_portal_views.client_favorites, name="bo_client_favorites"),
    path("client/favoris/toggle/<int:stock_id>/", client_portal_views.client_favorite_toggle, name="bo_client_favorite_toggle"),
    path("client/panier/", client_portal_views.client_cart, name="bo_client_cart"),
    path("client/panier/ajouter/<int:stock_id>/", client_portal_views.client_cart_add, name="bo_client_cart_add"),
    path("client/commander/", client_portal_views.client_checkout, name="bo_client_checkout"),
    path("client/commander/devis-assurance/", client_portal_views.client_checkout_insurance_quote, name="bo_client_checkout_insurance_quote"),
    path("client/forfaits/", client_portal_views.client_subscriptions, name="bo_client_subscriptions"),
    path("client/urgence/", client_portal_views.client_emergency, name="bo_client_emergency"),
    path("client/messagerie/", client_portal_views.client_messages, name="bo_client_messages"),
    path("client/messagerie/<slug:slug>/", client_portal_views.client_chat, name="bo_client_chat"),
    path("client/produit/<int:stock_id>/", client_portal_views.client_product, name="bo_client_product"),
    path("client/produit/<int:stock_id>/verifier-disponibilite/", client_portal_views.client_verify_stock, name="bo_client_verify_stock"),
    path("client/commande/<str:code>/confirme/", client_portal_views.client_order_confirmed, name="bo_client_order_confirmed"),
    path("client/commande/<str:code>/suivi/", client_portal_views.client_order_tracking, name="bo_client_order_tracking"),
    path(
        "client/commande/<str:code>/qr-livraison/",
        client_portal_views.client_delivery_qr,
        name="bo_client_order_delivery_qr",
    ),
]