# Generated by Django 6.1 on 2026-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_medicine_contenance_pharmacist_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='purchase_price',
            field=models.PositiveIntegerField(default=0, help_text="Prix d'achat FCFA (marge stats) — 0 = estimation auto"),
        ),
    ]
