# Generated by Django 6.1 on 2026-08-29 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pharmacy_portal_cdc'),
        ('pharmacies', '0004_pharmacy_personnel_erp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Validé'), ('cancelled', 'Annulé')], default='in_progress', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('lines_total', models.PositiveIntegerField(default=0)),
                ('lines_counted', models.PositiveIntegerField(default=0)),
                ('variance_lines', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sessions_completed', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to='pharmacies.pharmacy')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sessions_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'inventaire",
                'verbose_name_plural': "Sessions d'inventaire",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockInventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField()),
                ('counted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lines', to='catalog.pharmacystock')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.stockinventorysession')),
            ],
            options={
                'ordering': ['stock__medicine__name'],
                'unique_together': {('session', 'stock')},
            },
        ),
    ]
