# Generated by Django 6.1 on 2026-08-09 18:06

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=orders.models.generate_order_code, max_length=20, unique=True)),
                ('validation_code', models.CharField(default=orders.models.generate_validation_code, max_length=4)),
                ('status', models.CharField(choices=[('cart', 'Panier'), ('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'À préparer'), ('ready', 'Prête'), ('delivering', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='cart', max_length=20)),
                ('delivery_mode', models.CharField(choices=[('home', 'Livraison à domicile'), ('pickup', 'Retrait en pharmacie'), ('express', 'Livraison express')], default='home', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('delivery_fee', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('insurance_coverage', models.PositiveIntegerField(default=0)),
                ('deposit_amount', models.PositiveIntegerField(default=0, help_text='Acompte obligatoire COD')),
                ('total', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField()),
                ('medicine_name', models.CharField(max_length=200)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.medicine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prescriptions/')),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée'), ('used', 'Utilisée')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
