# Generated by Django 6.1 on 2026-08-09 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('pharmacies', '0002_document_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='linked_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_to_review', to='pharmacies.pharmacy'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Panier'), ('pending', 'En attente'), ('awaiting_rx', 'Ordonnance à valider'), ('confirmed', 'Confirmée'), ('preparing', 'À préparer'), ('ready', 'Prête'), ('delivering', 'En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='cart', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon (prévisualisation)'), ('pending', 'En attente de validation'), ('validated', 'Validée'), ('rejected', 'Rejetée'), ('used', 'Utilisée')], default='draft', max_length=20),
        ),
    ]
