# Generated by Django 6.1 on 2026-08-25 07:55

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='validation_code',
            field=models.CharField(default=orders.models.generate_validation_code, max_length=6),
        ),
    ]
