# Generated by Django 6.1 on 2026-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_validation_code_6digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, help_text='Début préparation — décompte affiché au client', null=True),
        ),
    ]
