# Generated by Django 6.1 on 2026-08-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pharmacy_portal_cdc'),
        ('payments', '0004_insurance_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='insurance_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.insuranceprovider'),
        ),
    ]
