# Generated by Django 6.1 on 2026-08-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loyaltyprogramsettings_loyaltyreward_and_more'),
        ('orders', '0006_insurance_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_discount',
            field=models.PositiveIntegerField(default=0, help_text='Réduction fidélité (bon ou palier)'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_orders', to='accounts.loyaltyvoucher'),
        ),
    ]
