# Generated by Django 6.1 on 2026-08-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_loyalty_discount_order_loyalty_voucher'),
        ('pharmacies', '0004_pharmacy_personnel_erp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_rating', models.PositiveSmallIntegerField()),
                ('pharmacy_comment', models.TextField(blank=True)),
                ('courier_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('courier_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_evaluations', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_evaluation', to='orders.order')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_evaluations', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'Évaluation commande',
                'verbose_name_plural': 'Évaluations commande',
                'ordering': ['-created_at'],
            },
        ),
    ]
