# Generated by Django 6.1 on 2026-08-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_emergency_pharmacy_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='escalated_to_support',
            field=models.BooleanField(default=False),
        ),
    ]
