# Generated by Django 6.1 on 2026-08-29 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_pharmacy_portal_cdc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_per_user', models.PositiveSmallIntegerField(default=8, help_text='Notifications marketing max / utilisateur / jour')),
                ('quiet_hours_start', models.TimeField(default='21:00')),
                ('quiet_hours_end', models.TimeField(default='07:00')),
                ('channel_sms_enabled', models.BooleanField(default=True)),
                ('channel_email_enabled', models.BooleanField(default=True)),
                ('channel_push_enabled', models.BooleanField(default=True)),
                ('channel_whatsapp_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres notifications plateforme',
                'verbose_name_plural': 'Paramètres notifications plateforme',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Attention'), ('error', 'Erreur'), ('order', 'Commande'), ('delivery', 'Livraison'), ('promo', 'Promotion'), ('health', 'Alerte sanitaire')], default='info', max_length=20)),
                ('audience', models.CharField(choices=[('all', 'Tous les utilisateurs'), ('clients', 'Clients'), ('pharmacists', 'Pharmaciens'), ('couriers', 'Livreurs')], default='all', max_length=20)),
                ('channels', models.JSONField(default=list, help_text='Liste : in_app, push, sms, email, whatsapp')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sending', 'En cours'), ('sent', 'Envoyée'), ('failed', 'Échouée')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('skipped', 'Ignoré'), ('throttled', 'Limité (fréquence)'), ('quiet', 'Hors plage horaire'), ('failed', 'Échec')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='notifications.notificationcampaign')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='notifications.notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False, help_text="Architecture prête — activation lors de l'intégration WhatsApp Business")),
                ('marketing_enabled', models.BooleanField(default=True, help_text='Promotions et informations non critiques')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
