# Generated by Django 6.1 on 2026-08-29 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='handoff_courier',
            field=models.ForeignKey(blank=True, help_text='Livreur remplaçant (en attente validation du code)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='transfer_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='transfer_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
